// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhLwLoyc8kRg8UyEEMTYwOgvVlDckHZE',
    appId: '1:528033703250:web:4d2360232a77248ac2068b',
    messagingSenderId: '528033703250',
    projectId: 'portfolioapp-neu-abdelkarim',
    authDomain: 'portfolioapp-neu-abdelkarim.firebaseapp.com',
    databaseURL: 'https://portfolioapp-neu-abdelkarim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolioapp-neu-abdelkarim.appspot.com',
    measurementId: 'G-ENKLR0PP2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1m-UxBYEFJBK2qe8lXAU2QdSdraFcKU',
    appId: '1:528033703250:android:ace155bfc97b3fabc2068b',
    messagingSenderId: '528033703250',
    projectId: 'portfolioapp-neu-abdelkarim',
    databaseURL: 'https://portfolioapp-neu-abdelkarim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolioapp-neu-abdelkarim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeegv8UPDm5n-LyKG3mF-B9el0cU1snQ',
    appId: '1:528033703250:ios:eb0542b5b1a8c19cc2068b',
    messagingSenderId: '528033703250',
    projectId: 'portfolioapp-neu-abdelkarim',
    databaseURL: 'https://portfolioapp-neu-abdelkarim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolioapp-neu-abdelkarim.appspot.com',
    iosBundleId: 'com.example.jo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeegv8UPDm5n-LyKG3mF-B9el0cU1snQ',
    appId: '1:528033703250:ios:eb0542b5b1a8c19cc2068b',
    messagingSenderId: '528033703250',
    projectId: 'portfolioapp-neu-abdelkarim',
    databaseURL: 'https://portfolioapp-neu-abdelkarim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolioapp-neu-abdelkarim.appspot.com',
    iosBundleId: 'com.example.jo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvhLwLoyc8kRg8UyEEMTYwOgvVlDckHZE',
    appId: '1:528033703250:web:7f70c45d635466fbc2068b',
    messagingSenderId: '528033703250',
    projectId: 'portfolioapp-neu-abdelkarim',
    authDomain: 'portfolioapp-neu-abdelkarim.firebaseapp.com',
    databaseURL: 'https://portfolioapp-neu-abdelkarim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolioapp-neu-abdelkarim.appspot.com',
    measurementId: 'G-SEGJV7TF8S',
  );
}
